// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfwxpydddmckmbrlrjqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd3hweWRkZG1ja21icmxyanFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzIxNTQsImV4cCI6MjA3MDI0ODE1NH0.dMSeDkj1t0TjmjNeWKKL5qaFN0hlaa0MOMJVi_xUrnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});